### ISSUE TITLE
dev-util/pmbootstrap should depend on sudo

### ISSUE THREAD

**Issue by dblsaiko** [jcaesar/liftm-overlay#1]
pmbootstrap calls sudo to set up chroots (maybe other things as well?) and fails when it's not installed, e.g. for me since I like to use doas instead.

**Comment by jcaesar** [comment]
Oh, wow, there's actually people using this… I guess I should slack less with the version updates. :)

I pushed a fix, can I ask you to confirm?

**Comment by dblsaiko** [comment]
Looks good, thanks!
